---
title: "User-Contributed Vignettes"
author: "Chester Ismay"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    df_print: kable
vignette: |
  %\VignetteIndexEntry{User-Contributed Vignettes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Due to CRAN space limitations on packages, user-contributed vignettes that walk through different analyses using the data sets in the `fivethirtyeight` and `fivethirtyeightdata` packages are linked below in this "vignette of vignettes." Each vignette has two links: 1) An HTML version of the vignette available at the `fivethirtyeightdata` package [website](https://fivethirtyeightdata.github.io/fivethirtyeightdata/index.html) under the Articles tab and 2) the corresponding `.Rmd` R Markdown source code available on GitHub.

- [Bechdel analysis using the `tidyverse`](https://fivethirtyeightdata.github.io/fivethirtyeightdata/articles/bechdel.html) by Chester Ismay [(Rmd)](https://raw.githubusercontent.com/fivethirtyeightdata/fivethirtyeightdata/master/vignettes/bechdel.Rmd)
- [Bob Ross - Joy of Painting](https://fivethirtyeightdata.github.io/fivethirtyeightdata/articles/bob_ross.html) by Jonathan Bouchet [(Rmd)](https://raw.githubusercontent.com/fivethirtyeightdata/fivethirtyeightdata/master/vignettes/bob_ross.Rmd)
- [Gender in Comic Books](https://fivethirtyeightdata.github.io/fivethirtyeightdata/articles/comics_gender.html) by Jonathan Bouchet [(Rmd)](https://raw.githubusercontent.com/fivethirtyeightdata/fivethirtyeightdata/master/vignettes/comics_gender.Rmd)
- [How Many Fucks Does Tarantino Give?](https://fivethirtyeightdata.github.io/fivethirtyeightdata/articles/tarantino_swears.html) by Olivia Barrows, Jojo Miller, and Jayla Nakayama [(Rmd)](https://raw.githubusercontent.com/fivethirtyeightdata/fivethirtyeightdata/master/vignettes/tarantino_swears.Rmd)
- [Looking at the Biopics of Hollywood](https://fivethirtyeightdata.github.io/fivethirtyeightdata/articles/biopics.html) by Pradeep Adhokshaja [(Rmd)](https://raw.githubusercontent.com/fivethirtyeightdata/fivethirtyeightdata/master/vignettes/biopics.Rmd)
- [2015 NBA player predictions analysis using the `tidyverse`](https://fivethirtyeightdata.github.io/fivethirtyeightdata/articles/NBA.html) by G. Elliott Morris (with support from Chester Ismay) [(Rmd)](https://raw.githubusercontent.com/fivethirtyeightdata/fivethirtyeightdata/master/vignettes/NBA.Rmd)
- [Trump Twitter analysis using the `tidyverse`](https://fivethirtyeightdata.github.io/fivethirtyeightdata/articles/trump_twitter.html) by Adam Spannbauer (with support from Jennifer Chunn) [(Rmd)](https://raw.githubusercontent.com/fivethirtyeightdata/fivethirtyeightdata/master/vignettes/trump_twitter.Rmd)

You can also install a version of the package that includes all the above vignettes by installing the `fivethirtyeightdata` package and then view a list of all vignettes:

```{r install, eval=FALSE}
install.packages("fivethirtyeightdata",
  repos = "https://fivethirtyeightdata.github.io/drat/",
  type = "source")
vignette(package = "fivethirtyeightdata")
```
